In [1]:
import pandas as pd

In [9]:
# Melt & Pivot

df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2028, 2021, 2020, 2021],
    "sales": [108, 120, 90, 110],
    "profit": [20, 25, 18, 22]
})

melted_df = df.melt(
    id_vars = ["country", "year"],
    value_vars = ["sales", "profit"],
    var_name = "metrics",
    value_name = "value"
)

melted_df.pivot(
    index = ["country", "year"],
    columns = "metrics",
    values = "value"
)

metrics       profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2021      25    120
        2028      20    108

In [8]:
df

  country  year  sales  profit  tax
0     USA  2028    108      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40